name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Set up .cargo/config.toml
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << EOF
          [build]
          rustflags = ["-C", "target-cpu=native"]

          [target.x86_64-apple-darwin]
          rustflags = ["-C", "target-cpu=native"]
          EOF

      - name: Build with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          # https://github.com/tauri-apps/tauri-action/issues/740
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseBody: |
            Powerflow v__VERSION__
            
            支持macOS 10.15+，仅支持Intel芯片。
            
            ### 安装方法
            下载DMG文件，打开并将应用拖到Applications文件夹中。
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }}
