name: development-build

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Set up .cargo/config.toml
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << EOF
          [build]
          rustflags = ["-C", "target-cpu=native"]

          [target.x86_64-apple-darwin]
          rustflags = ["-C", "target-cpu=native"]
          EOF

      - name: Build with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeDebug: true
          args: --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powerflow-macos
          path: |
            src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: error 